{% set name = "orange-spectroscopy" %}
{% set version = "0.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a229d5095e31a354da47b99f2c04f349daf83508dad8587d1ba05e6810583127

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
    - recommonmark
    - pip
  run:
    - python >=3.9
    - setuptools >=36.3
    - pip >=9.0
    - numpy >=1.20.0
    - orange3 >=3.34.0
    - orange-canvas-core >=0.1.28
    - orange-widget-base >=4.19.0
    - scipy >=1.9.0
    - scikit-learn >=1.0.1
    - spectral >=0.22.3,!=0.23
    - serverfiles >=0.2
    - anyqt >=0.1.0
    - pyqtgraph >=0.12.2,!=0.12.4
    - colorcet
    - h5py
    - extranormal3 >=0.0.3
    - renishaw_wire >=0.1.8
    - pillow
    - lmfit >=1.0.2
    - bottleneck
    - pebble
    - agilent-format >=0.4.5

test:
  imports:
    - orangecontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Quasars/orange-spectroscopy
  summary: Extends Orange to handle spectral and hyperspectral analysis.
  license: Unlicense
  license_file: LICENSE
  description: Orange add-on for spectral data analysis. Provides spectra and hyperspectra plotting, interpolation, preprocessing (cutting, smoothing, normalization), and integration. Supports common spectral file formats.
  dev_url: https://github.com/Quasars/orange-spectroscopy
  doc_url: https://orange-spectroscopy.readthedocs.io/

extra:
  recipe-maintainers:
    - HeavyTony2
