{% set name = "orange-spectroscopy" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Orange-Spectroscopy-{{ version }}.tar.gz
  sha256: 71e2663204505f4137ddaaee38c838250e98ed5ab4446836eeeb7e5d92f00cb1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - setuptools >=36.3
    - anyqt >=0.0.6
    - arm_pyart
    - bottleneck
    - colorcet
    - extranormal3 >=0.0.3
    - h5py
    - lmfit >=1.0.2
    - numpy >=1.18.0
    - orange-canvas-core >=0.1.24
    - orange-widget-base >=4.16.1
    - orange3 >=3.31.0
    - pebble
    - pillow
    - pyqt
    - pyqtgraph >=0.11.1,!=0.12.4
    - renishaw_wire >=0.1.8
    - python >=3.9
    - scipy >=0.14.0
    - scikit-learn
    - serverfiles >=0.2
    - spectral >=0.18,!=0.23

test:
  imports:
    - orangecontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Quasars/orange-spectroscopy
  summary: Extends Orange to handle spectral and hyperspectral analysis.
  license: Unlicense
  license_file: LICENSE
  description: Orange add-on for spectral data analysis. Provides spectra and hyperspectra plotting, interpolation, preprocessing (cutting, smoothing, normalization), and integration. Supports common spectral file formats.
  dev_url: https://github.com/Quasars/orange-spectroscopy
  doc_url: https://orange-spectroscopy.readthedocs.io/

extra:
  recipe-maintainers:
    - HeavyTony2
